---
version: '2'
services:
  kafka-sidecar:
    image: networknt/kafka-sidecar:2.0.30
    depends_on:
      - sidecar-backend
    volumes:
      - ./config/docker:/config
    ports:
      - 8443:8443
    hostname: kafka-sidecar
    network_mode: host
    container_name: kafka-sidecar

  sidecar-backend:
    image: networknt/sidecar-backend-1.0.0:2.0.30
    ports:
      - 8444:8444
    hostname: sidecar-backend
    network_mode: host
    container_name: sidecar-backend
