#--------------------------------------------------------------------------------
# values.yml : Set of values commonly overridden in microservices
#--------------------------------------------------------------------------------

#--------------------------------------------------------------------------------
# client.yml
#--------------------------------------------------------------------------------

#--------------------------------------------------------------------------------
# server.yml
server.serviceId: com.networknt.kafka-sidecar-1.0.0
#--------------------------------------------------------------------------------

#--------------------------------------------------------------------------------
# security.yml
#--------------------------------------------------------------------------------
# Enable JWT verification flag.
# security.enableVerifyJwt: true

# Service Startup and Shutdown Hooks
service.com.networknt.server.StartupHookProvider:
  - com.networknt.mesh.kafka.ProducerStartupHook
  # - com.networknt.mesh.kafka.ActiveConsumerStartupHook
  # - com.networknt.mesh.kafka.KsqldbReactiveConsumerStartupHook
  - com.networknt.mesh.kafka.KsqldbActiveConsumerStartupHook
  - com.networknt.mesh.kafka.ReactiveConsumerStartupHook
  - com.networknt.mesh.kafka.AdminClientStartupHook
  - com.networknt.mesh.kafka.AuditProducerStartupHook
service.com.networknt.server.ShutdownHookProvider:
  - com.networknt.mesh.kafka.ProducerShutdownHook
  # - com.networknt.mesh.kafka.ActiveConsumerShutdownHook
  # - com.networknt.mesh.kafka.KsqldbReactiveConsumerShutdownHook
  - com.networknt.mesh.kafka.KsqldbActiveConsumerShutdownHook
  - com.networknt.mesh.kafka.ReactiveConsumerShutdownHook
  - com.networknt.mesh.kafka.AdminClientShutdownHook
  - com.networknt.mesh.kafka.AuditProducerShutdownHook
